name: UnitTest
on:
  push:
    branches:
      - SOM-Database
  pull_request:
    branches:
      - SOM-Database

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies&Run Unit Testing&Check code covergae
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          cd Backend
          pytest 
          pip install coverage
          coverage run test_app.py
          coverage report
          
