name: UnitTest
on:
  push:
    branches:
      - Rebuud-code
  pull_request:
    branches:
      - Rebuud-code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies&Run Unit Testing
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          cd Flask-backend 
          pytest 